apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: {{ .PluginName }}
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/{{ .Owner }}/{{ .Repo }}/releases/download/v0.1.0/{{ .PluginName }}_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./{{ .PluginName }}"
      to: "."
    bin: "{{ .PluginName }}"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/{{ .Owner }}/{{ .Repo }}/releases/download/v0.1.0/{{ .PluginName }}_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./{{ .PluginName }}"
      to: "."
    bin: "{{ .PluginName }}"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/{{ .Owner }}/{{ .Repo }}/releases/download/v0.1.0/{{ .PluginName }}_windows_amd64.zip
    sha256: ""
    files:
    - from: "/{{ .PluginName }}.exe"
      to: "."
    bin: "{{ .PluginName }}.exe"
  shortDescription: A new plugin
  homepage: https://github.com/{{ .Owner }}/{{ .Repo }}
  caveats: |
    Usage:
      $ kubectl {{ .PluginName }}

    For additional options:
      $ kubectl {{ .PluginName }} --help
      or https://github.com/{{ .Owner }}/{{ .Repo }}/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
